### ISSUE TITLE
Generalize package to support approximate nearest neighbors

### ISSUE THREAD

**Issue by LTLA** [LTLA/kmknn#1]
I'm thinking of generalizing the package to support approximate nearest neighbor matching via _RcppAnnoy_. This would provide users with the option of sacrificing accuracy for much greater speed. However, assuming this is possible, there are multiple logistical issues that need to be resolved:

- As the package would involve multiple algorithms, I would like to rename it. Open to suggestions, but if no one gives me any, _ramsay_ would be a good choice... because good neighbors become good friends.
- I'm trying to think of an unobtrusive way for users to indicate that they would like to use an approximate algorithm in `findKNN`. One option may be to simply have a parameter object specifying the algorithm to be used, similar to `BiocParallelParam` objects. Another possibility would be to use a global option that gets looked up, though I'm reluctant to rely on a lot of arguments in the globals.

Tagging @mtmorgan for some logistical advice. Also tagging @kasperdanielhansen, who probably has similar issues with a general-purpose wrapper that includes both approximate and exact PCA.

**Comment by PeteHaitch** [comment]
+1 for *ramsay* even if the joke is only got by people in Oz and the UK

**Comment by mtmorgan** [comment]
I'd avoid global variables -- write 'functional'-style functions. The *Param approach seems like a reasonable way to make a complex configuration and apply it repeatedly.

**Comment by LTLA** [comment]
Okay, this is underway. A complication is that it is possible to precompute indices in `buildNNIndex` and pass them to `findKNN`. However, the nature of the precomputed indices will differ between algorithms. I am thinking that the best approach would be to:

- Define `*Param` classes as previously described, to specify the type of algorithm and various details.
- Define `*Index` classes that describe the indices, specialized for different algorithms.
- Define S4 methods that only take the correct combination of `Param` and `Index` (either can be missing, but you can't specify a `Param` for one algorithm with an `Index` for another).

Is this the simplest way to go about this? Seems like an awful lot of classes to throw around. Alternatively, I could also store the precomputed information in `Param`, but that doesn't seem right as the `Param` class should not be specific to a particular data set while the `Index` class will be.

Also (**sigh**), I guess a more sober name would be _BiocNeighbors_.

**Comment by LTLA** [comment]
Okay, code and docs are done - only tests are left. @mtmorgan, could I ask for a mini-review of how I've set up the S4 classes and methods in the `annoyance` branch? I have followed the scheme described in my previous post. Of particular concern is `findKNN.R` and `queryKNN.R`, the logic here is that:

- You can specify either of `BNINDEX` or `BNPARAM` (leaving the other as `NULL`), and the dispatch mechanism will be able to work out which algorithm should be used based on the supplied classes.
- You can also specify both arguments, but these should ask for dispatch to the same algorithm.
- The generic has defaults for both arguments that need to be respected.

The current set-up seems rather complex as I need to define a separate method for each combination of allowable values for the two arguments above. Not sure if this can be avoided.
