### ISSUE TITLE
Add "cosine" metric to "Annoy" class. 

### ISSUE THREAD

**Issue by yzizhen** [LTLA/kmknn#19]
I am interested in testing the "cosine" distance metric for KNN. Is it possible to add this option to the class?

**Comment by LTLA** [comment]
Hm... Well, it wouldn't be hard for Annoy. But I can't remember if this is supported by HNSW, and it would also need to be added to the VP-tree and KMKNN implementations. Otherwise a hypothetical `distance="cosine"` wouldn't work consistently for all methods.

In fact, I'm pretty sure that cosine distances wouldn't work for the exact methods, because it's not a true distance metric and so the triangle inequality doesn't hold. This breaks the assumptions required by those algorithms. So I guess it would only be relevant for the approximate methods and for the exhaustive method.

Is there a specific reason you need the cosine distance, or is this just for your curiosity?

**Comment by yzizhen** [comment]
Thank you so much for your quick response.

In some cases, 1 - correlation seems to work better than euclidean
distance. For example, the UMAP created for single cell studies using the
"correlation" metric makes more sense than the one based on euclidean
distance. Not sure exactly why, but off/on binary gene expression
differences seem to contribute more to the overall distance, which tend to
be the most robust biological signals. I am curious to do a more systematic
comparison to see if it is the case indeed. On the other hand, I am not
sure how good is the approximation by Annoy using this metric in the high
dimensional space.

What's your experience with HNSW? It was fast, but I tested once and
compared with RANN:::nn2 function. The returned KNNs by HNSW have much
bigger distances, so I abandoned it despite obvious gain in efficiency.

**Comment by LTLA** [comment]
> In some cases, 1 - correlation seems to work better than euclidean distance. For example, the UMAP created for single cell studies using the "correlation" metric makes more sense than the one based on euclidean distance. Not sure exactly why, but off/on binary gene expression differences seem to contribute more to the overall distance, which tend to be the most robust biological signals. I am curious to do a more systematic comparison to see if it is the case indeed. On the other hand, I am not sure how good is the approximation by Annoy using this metric in the high dimensional space.

Very interesting. I'm guessing you did this on the expression values, i.e., without any prior compression in PC space? I don't know what this would mean to use non-Euclidean distances in PC space.

> What's your experience with HNSW? It was fast, but I tested once and compared with RANN:::nn2 function. The returned KNNs by HNSW have much bigger distances, so I abandoned it despite obvious gain in efficiency.

TBH haven't really used it much, I usually use Annoy for my approximations.

Anyway, if you want this feature, you can get the ball rolling by making a PR. It should be fairly easy for Annoy, at least; I can talk you through the rest.

**Comment by yzizhen** [comment]
I am planning to use it on expression values. Agree that it doesn't make
much sense in PC space, but UMAP applied in PC space using "correlation"
metric somehow works great. I now use it as default, and Seurat seems to
make the same decision.

Do you recommend me to add the new function directly to the package and
submit pull requests when it is ready?  Not comfortable messing with
somebody else's code but I will give it a try.

Thanks

**Comment by LTLA** [comment]
I don't really see much differences between the various UMAP parametrizations... they all look like rainbow vomit to me. Oh well.

But anyway, if you just want to want to use distances derived from correlations, there's an easy transformation of the input values to achieve this effect without requiring software changes - see https://arxiv.org/abs/1208.3145. Would this suffice?

> Do you recommend me to add the new function directly to the package and submit pull requests when it is ready?

These would be C++ modifications, involving the creation of a new class for templating. Is that something you're comfortable with?

**Comment by yzizhen** [comment]
The transformation of distance is not what I am looking for.
I can write C++ code with the Rcpp library, though I am not very
proficient. I can see where the change needs to be made in the code, but
prefer not to do it unless I have to. I think it should be a very easy fix
for you.

Thanks!

**Comment by LTLA** [comment]
> The transformation of distance is not what I am looking for.

Should be pretty close, though. "Correlation distance" is `1 - r` for Pearson/Spearman correlation `r`, while the metrics defined in that paper are `sqrt(0.5 * (1 - r))` and can be computed as Euclidean distances on scaled/centered inputs. The latter is also a true distance metric, and thus works with the exact search algorithms, while the former is not.

Anyway, that's just something to consider before embarking on software-level changes.

**Comment by yzizhen** [comment]
Hi, Aaron

If I understand the paper correctly, you can easily transform the
cosine/corrfelation into metric distance, but in order to use KNN algorithm
on Euclidean distance, we need to transform the original input data
matrix,  because we can't touch the internal euclidean distance calculation
within the KNN algorithm. The distance needs to be computed on the fly, as
we don't have space to keep them for large datasets.  Please correct me if
I'm wrong.

Thanks

**Comment by LTLA** [comment]
Hm. Note that you'll already be making a series of copies:

- Any subsetting to HVGs, normalization, transformation, etc. will be making copies, unless you're using a `DelayedArray`.
- For the usual gene expression matrices with cells in the columns, you'll need be doing a transposition before feeding it into **BiocNeighbors** if you want to find neighbors among cells; this is yet another copy, unless you're using a `DelayedArray`.
- **BiocNeighbors** itself requires an ordinary matrix as input, so if you've got some other matrix class (e.g., sparse, file-backed, whatever), you'll need to call `as.matrix()` anyway to create a dense copy.
- IIRC Annoy will also store a dense copy of the input matrix in its own allocated memory.

So in the big scheme of things, an extra copy isn't really a big deal. Even if you have 100000 cells, if you subset to some subset of, say, 2000 HVGs, then even as an ordinary matrix, you'll only need 1.6 GB of RAM; this should not be particularly challenging. If you have larger datasets, you should really consider compressing the data with PCA beforehand.

**Comment by yzizhen** [comment]
Hi, Aaron

I finally found the time to add "cosine" distance to Annoy. It served my
purpose well. I am wondering if I should try to submit my change to your
repository, or I should host it somewhere else.

Thank you for your advice in advance.

Best
Zizhen

**Comment by LTLA** [comment]
I ruminated on this for a while and I concluded that I would prefer to compute Euclidean distances on L2-normalized values (which, incidentally, is exactly the implementation used internally by Annoy, based on its [README](https://github.com/spotify/annoy)). This would allow me to provide `method="cosine"` to all methods, not just Annoy; it would also reduce the compilation time and library size by avoiding the need to instantiate another instance of the templated Annoy functions. The memory overhead of making a copy is negligible though it can be further reduced by doing the normalization in C++ to avoid an extra copy of the matrix.

**Comment by yzizhen** [comment]
Hi, Aaron

Thanks for the explanation. All sounds good to me. Please let me know when
the new features are available.

Best
Zizhen

**Comment by LTLA** [comment]
Done in 1.9.5, 8385e1dab16c87b17a041bbcba27c7e24ff96d6a.

**Comment by yzizhen** [comment]
Thanks a lot, Aaron.
The conversion can add considerable overhead for a very large matrix, but I
usually process queries by trunks so it is manageable.

Best
Zizhen

**Comment by LTLA** [comment]
How big are we talking about here? I've never had cause to deal with a dense matrix greater than 1 GB in size.

**Comment by yzizhen** [comment]
The matrix can go up to 10-20G or more in future. If the copy can be
avoided, there is also less memory concern to parallelize the operation.

**Comment by LTLA** [comment]
I don't mind writing some extra code to skip this particular copy, but as I said before, copies are made liberally elsewhere:

- The default `transposed=FALSE` makes a copy to transpose things to a more cache-friendly format.
- Now that you mention it, parallelization will also make a copy in the form of multiple chunks to be distributed to each worker.
- Annoy itself stores a copy of the data, though I don't know how this is split between the index file and RAM.

The underlying design philosophy in **BiocNeighbors** is that speed is more important than memory usage. If this is to be changed, it would require some effort, and I don't have a strong reason for doing so at the moment.

TBH, if you're working with single-cell data, it really sounds like you should be compressing your input matrix; I've never had a use case where I had to work with a 10 GB dense matrix, even when dealing with million-cell datasets. A PCA on the L2-normalized matrix followed by a Euclidean distance NN search on the first 50 PCs should be a pretty good proxy to a direct cosine distance-based search, given that the Euclidean distances in PC space approximate the input distances.
