### ISSUE TITLE
BiocNeighbors compilation fails on R 3.6

### ISSUE THREAD

**Issue by johebll** [LTLA/kmknn#20]
Hello,
i am currently facing issues installing "BiocNeighbors",
using: 
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.0 (2019-04-26)

The compilation fails like this:
<pre>
> BiocManager::install("BiocNeighbors")
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.0 (2019-04-26)
Installing package(s) 'BiocNeighbors'
trying URL 'https://bioconductor.org/packages/3.10/bioc/src/contrib/BiocNeighbors_1.4.2.tar.gz'
Content type 'application/x-gzip' length 902918 bytes (881 KB)
==================================================
downloaded 881 KB

* installing *source* package ‘BiocNeighbors’ ...
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppAnnoy/include" -I"/usr/lib64/R/library/RcppHNSW/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/RcppAnnoy/include" -I"/usr/lib64/R/library/RcppHNSW/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c annoy.cpp -o annoy.o
In file included from annoy.cpp:1:0:
annoy.h:33:63: error: wrong number of template arguments (4, should be 5)
     typedef AnnoyIndex<Index_t, Data_t, Distance, Kiss64Random> _index;
                                                               ^
In file included from annoy.h:17:0,
                 from annoy.cpp:1:
/usr/lib64/R/library/RcppAnnoy/include/annoylib.h:845:9: error: provided for ‘template<class S, class T, class Distance, class Random, class ThreadedBuildPolicy> class AnnoyIndex’
   class AnnoyIndex : public AnnoyIndexInterface<S, T, 
         ^
annoy.cpp: In constructor ‘Annoy<Distance>::Annoy(int, const string&, double)’:
annoy.cpp:7:9: error: request for member ‘load’ in ‘((Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘Annoy<Distance>::_index {aka int}’
     obj.load(fname.c_str());
         ^
annoy.cpp: In member function ‘MatDim_t Annoy<Distance>::get_nobs() const’:
annoy.cpp:16:16: error: request for member ‘get_n_items’ in ‘((const Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘const _index {aka const int}’
     return obj.get_n_items();
                ^
annoy.cpp: In member function ‘void Annoy<Distance>::find_nearest_neighbors(CellIndex_t, NumNeighbors_t, bool, bool)’:
annoy.cpp:44:9: error: request for member ‘get_nns_by_item’ in ‘((Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘Annoy<Distance>::_index {aka int}’
     obj.get_nns_by_item(c, K + 1, get_search_k(K + 1), &kept_idx, dptr); // +1, as it forgets to discard 'self'.
         ^
annoy.cpp: In member function ‘void Annoy<Distance>::find_nearest_neighbors(const double*, NumNeighbors_t, bool, bool)’:
annoy.cpp:86:9: error: request for member ‘get_nns_by_vector’ in ‘((Annoy<Distance>*)this)->Annoy<Distance>::obj’, which is of non-class type ‘Annoy<Distance>::_index {aka int}’
     obj.get_nns_by_vector(holding.data(), K, get_search_k(K), &kept_idx, dptr);
         ^
In file included from annoy.cpp:97:0:
build_annoy.cpp: In instantiation of ‘Rcpp::RObject build_annoy_internal(Rcpp::NumericMatrix, int, const string&) [with Distance = Manhattan; Rcpp::RObject = Rcpp::RObject_Impl<Rcpp::PreserveStorage>; Rcpp::NumericMatrix = Rcpp::Matrix<14>; std::string = std::basic_string<char>]’:
build_annoy.cpp:26:66:   required from here
build_annoy.cpp:14:9: error: request for member ‘add_item’ in ‘obj’, which is of non-class type ‘Annoy<Manhattan>::_index {aka int}’
         obj.add_item(i, tmp.data());
         ^
build_annoy.cpp:17:5: error: request for member ‘build’ in ‘obj’, which is of non-class type ‘Annoy<Manhattan>::_index {aka int}’
     obj.build(Ntrees);
     ^
build_annoy.cpp:18:5: error: request for member ‘save’ in ‘obj’, which is of non-class type ‘Annoy<Manhattan>::_index {aka int}’
     obj.save(Fname.c_str());
     ^
build_annoy.cpp: In instantiation of ‘Rcpp::RObject build_annoy_internal(Rcpp::NumericMatrix, int, const string&) [with Distance = Euclidean; Rcpp::RObject = Rcpp::RObject_Impl<Rcpp::PreserveStorage>; Rcpp::NumericMatrix = Rcpp::Matrix<14>; std::string = std::basic_string<char>]’:
build_annoy.cpp:28:66:   required from here
build_annoy.cpp:14:9: error: request for member ‘add_item’ in ‘obj’, which is of non-class type ‘Annoy<Euclidean>::_index {aka int}’
         obj.add_item(i, tmp.data());
         ^
build_annoy.cpp:17:5: error: request for member ‘build’ in ‘obj’, which is of non-class type ‘Annoy<Euclidean>::_index {aka int}’
     obj.build(Ntrees);
     ^
build_annoy.cpp:18:5: error: request for member ‘save’ in ‘obj’, which is of non-class type ‘Annoy<Euclidean>::_index {aka int}’
     obj.save(Fname.c_str());
     ^
annoy.cpp: In member function ‘MatDim_t Annoy<Distance>::get_nobs() const [with Distance = Manhattan; MatDim_t = int]’:
annoy.cpp:17:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
annoy.cpp: In member function ‘MatDim_t Annoy<Distance>::get_nobs() const [with Distance = Euclidean; MatDim_t = int]’:
annoy.cpp:17:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [annoy.o] Error 1
ERROR: compilation failed for package ‘BiocNeighbors’
* removing ‘/usr/lib64/R/library/BiocNeighbors’

The downloaded source packages are in
	‘/tmp/Rtmp5kwzZS/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(...) :
  installation of package ‘BiocNeighbors’ had non-zero exit status
> 
</pre>
I tried with reinstaling RcppAnnoy (successfully), but the problem persists...

Do you have an idea?
Best

**Comment by LTLA** [comment]
See the discussion in #17 for an explanation and solution.

**Comment by johebll** [comment]
Hello Aaron,

thank you very much for your help!
As you proposed: 
downgrading from RcppAnnoy 0.0.18 to 0.0.16 allowed me to 
install "BiocNeighbors BiocNeighbors 1.4.2"!

Great!

Am i right concluding that i have to freeze this version "RcppAnnoy 0.0.16" now for the future of this installation?

Best

**Comment by LTLA** [comment]
> Am i right concluding that i have to freeze this version "RcppAnnoy 0.0.16" now for the future of this installation?

That's right. Hopefully this will not be necessary for future versions of **BiocNeighbors**, but it is what it is right now.

**Comment by johebll** [comment]
Hello Aaron,
thank you again for your quick and great help!
