### ISSUE TITLE
Unit test failure on Mac arm64

### ISSUE THREAD

**Issue by hpages** [LTLA/kmknn#21]
Looks like **BiocNeighbors**'s unit tests have been failing on Mac arm64 for a while (6 months at least): https://bioconductor.org/checkResults/3.18/bioc-mac-arm64-LATEST/BiocNeighbors/kjohnson1-checksrc.html

As a consequence there's no Mac arm64 binary for the package in BioC 3.18: https://bioconductor.org/packages/3.18/BiocNeighbors

Note that this missing binary is currently blocking the propagation of Mac arm64 binaries for 63 Bioconductor packages that depend directly or indirectly on **BiocNeighbors** in BioC 3.18.

@LTLA Do you think you could take a look at the unit tests? Hopefully it's just a matter of relaxing the expected floating point precision of the results.

Thanks,
H.

**Comment by LTLA** [comment]
Relaxed by several orders of magnitude, let's see how it goes in 1.21.1.

**Comment by hpages** [comment]
Can you please push this to the `RELEASE_3_18` branch? The goal is to produce a Mac arm64 binary for the BioC 3.18 release. Our Mac arm64 builder for `devel` is not ready yet. Thanks!

**Comment by LTLA** [comment]
Done.

**Comment by hpages** [comment]
Awesome thanks! Let see what happens on the next build report for kjohnson1 (should be tomorrow, these arm64 Mac builders are super slow and can only build twice a week).

**Comment by hpages** [comment]
https://bioconductor.org/packages/3.18/BiocNeighbors :tada:
