### ISSUE TITLE
shared nearest neighbor graph directly from BiocNeighbors

### ISSUE THREAD

**Issue by sa-lee** [LTLA/kmknn#7]
Hi Aaron,

Just wondering if there'd be any scope to abstract out `scran::buildSNNGraph` to this pacakge or to provide a method in this package for constructing a SNN graph directly from a matrix of neighbor indices or a `BNIndex` object? 

Thanks,
Stuart

**Comment by LTLA** [comment]
Well, it wouldn't go in this package. If I were to abstract it out, it would go into _scran_, but perhaps you should describe why you need it abstracted - the NN search is usually fast enough.

**Comment by sa-lee** [comment]
I'm interested in retrieving the SNNgraph object from when you have already computed the NN search.  Looking over the source code for scran - I guess this is just exporting the `build_snn_rank` and `build_snn_number` functions. Apologies if there's already a way to do this from scran.

**Comment by LTLA** [comment]
Done in MarioniLab/scran@a57667bb194a99a6a1ab0d3ab01fce57bc97ff55, version 1.13.21.

**Comment by sa-lee** [comment]
Thanks!
