### ISSUE TITLE
Error in nn.d^2 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by MediciPrime** [LTLA/kmknn#9]
Hi @LTLA,

Just a heads up that BiocNeighbors version 1.3.5 causes the error in the title of this issue.  I needed to revert to version 1.3.3 in order to avoid that error.  Other than this your rewrite of SingleR is awesome, thank you so much for doing that!

All the best,
Behram

**Comment by LTLA** [comment]
This seems to be the same as #8.

**Comment by MediciPrime** [comment]
Oh I didn't notice, sorry!
